export const LOAD_SIMPSONS_SUCCESS = "LOAD_SIMPSONS_SUCCESS";
export const GET_EPISODE_SUCCESS = "GET_EPISODE_SUCCESS";
export const GET_MISSING_SUCCESS = "GET_MISSING_SUCCESS";
export const GET_SEASON_SUCCESS = "GET_SEASON_SUCCESS";